<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.awk</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>AWK</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#.*\n</string>
			<key>name</key>
			<string>comment.line.number-sign.awk.sharp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(close|fflush|getline|next|nextfile|print|printf|break|continue|do|while|if|exit|return|delete|function|system)\b</string>
			<key>name</key>
			<string>keyword.other.awk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(FILENAME|FS|NF|NR|OFMT|OFS|ORS|RS|ARGV|ARGC|)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s(\-\w[\w\-]*)|(\-\-\w+[\w\-]+)</string>
			<key>name</key>
			<string>support.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+\.\d+\.\d+\.\d+\b</string>
			<key>name</key>
			<string>constant.other.awk.ip</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$\d+</string>
			<key>name</key>
			<string>constant.other.awk.builtin</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(BEGIN|END)\b</string>
			<key>name</key>
			<string>entity.name.awk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[=|:]</string>
			<key>name</key>
			<string>punctuation.separator</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.awk</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.awk</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.awk</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.awk</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.awk</string>
	<key>uuid</key>
	<string>EBB315BE-900F-4853-89DF-AA208C8FDB39</string>
</dict>
</plist>
